name: py310img

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 11 * * 2'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Gather metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            shivupa/cclib-ci
          flavor: |
            latest=true
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}},prefix=py310-
            type=sha,prefix=py310-
            type=edge,prefix=py310-
      -
        name: Gather metadata for branch
        id: meta-branch
        uses: docker/metadata-action@v4
        with:
          images: |
            shivupa/cclib-ci
          flavor: |
            latest=auto
          tags: |
            type=ref,event=pull_request,prefix=py310-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: py310
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push on merge
        uses: docker/build-push-action@v3
        with:
          context: py310
          push: ${{ github.event_name != 'pull_request'}}
          tags: ${{ steps.meta.outputs.tags }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: py310
          push: true
          tags: ${{ steps.meta-branch.outputs.tags }}
