name: py37img

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 11 * * 2'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            shivupa/cclib-ci
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: py37
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            shivupa/cclib-ci:py37
